### ISSUE TITLE
ecash pool help needed

### ISSUE THREAD

**Issue by goodthebest** [Bitcoin-ABC/ecash-ckpool-solo#4]

**Comment by Fabcien** [comment]
eCash coinbase transactions need to include the miner fund output and the staking reward output. I can provide assistance to implement this in the mining software, however I will not do it myself.
The telegram dev group is a better place to exchange if you are willing to add the eCash support yourself, and I will be happy to answer your questions there. You will find the link in the Bitcoin ABC contributing document: https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/CONTRIBUTING.md

**Comment by goodthebest** [comment]
Thank you dear @Fabcien for your quick response.  Unfortunately, I'm not able to reach you via telegram I joined group but I'm not able to send message there for some unknown reason.

I'll appreciate as much as cooperation you can extend, I'm not a hardcore programmer but I can work around usually. Here are the minerfund coded comments in Miningcore please have a look, if possible you can add comments/code and send me pull request from there.

https://github.com/goodthebest/miningcoreXEC/commit/f0b353d40d722a8f7c573104ee42c444949ac0e6

**Comment by goodthebest** [comment]
https://t.me/goodthebest
here's my telegram for DM as I can't reach you there.
